version: "3.8"
services:

  beehive-manager:
    image: etherna/beehive-manager:latest
    environment:
      - ConnectionStrings__BeehiveManagerDb=mongodb://mongo/beehive                 # application db
      - ConnectionStrings__DataProtectionDb=mongodb://mongo/beehiveDataProtection   # system db
      - ConnectionStrings__HangfireDb=mongodb://mongo/beehiveHangfire               # async worker db
    networks:
      - mongo-net
    ports:
      - 80:80
    restart: unless-stopped

  mongo:
    hostname: mongo
    image: mongo:5.0
    volumes:
      - mongo-configdb:/data/configdb
      - mongo-db:/data/db
    networks:
      - mongo-net
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]

networks:
  mongo-net:
  
volumes:
  mongo-configdb:
  mongo-db:
